# Generated by Django 6.0 on 2026-08-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand_supply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandsupplyscanresult',
            name='strongest_zone_score',
            field=models.FloatField(db_index=True, default=0.0, help_text='Highest zone strength score out of 7/14 across all detected zones'),
        ),
        migrations.AlterField(
            model_name='demandsupplyzone',
            name='strength_score',
            field=models.FloatField(default=0.0, help_text='Zone strength score out of 7 (Core) or 14 (Expanded)'),
        ),
    ]
