"""
demand_supply/nifty500.py

Complete Nifty 500 constituent list (NSE symbols, as of July 2026).
Used to restrict scans to the Nifty 500 universe only.

Source: NSE India — Nifty 500 Index
"""

NIFTY_500 = [
    "360ONE", "3MINDIA", "ABB", "ABBOTINDIA", "ABCAPITAL", "ABFRL", "ABSL", "ACC",
    "ACMESOLAR", "ADANIENSOL", "ADANIENT", "ADANIGREEN", "ADANIPORTS", "ADANIPOWER",
    "ATGL", "ADANITRANS", "AIAENG", "AJANTPHARM", "AKUMS", "ALKEM", "ALLCARGO",
    "AMARAJABAT", "AMBUJACEM", "ANANDRATHI", "ANGELONE", "ANURAS", "APARINDS",
    "APOLLOHOSP", "APOLLOTYRE", "APTUS", "ARVSMART", "ASAHIINDIA", "ASHOKLEY",
    "ASIANPAINT", "ASTERDM", "ASTRAL", "ASTRAZEN", "ATKINS", "AUBANK", "AUROPHARMA",
    "AVANTIFEED", "AVENUE", "AXISBANK",
    "BAJAJ-AUTO", "BAJAJFINSV", "BAJAJHLDNG", "BAJFINANCE", "BALKRISIND",
    "BALRAMCHIN", "BANDHANBNK", "BANKBARODA", "BANKINDIA", "BATAINDIA", "BAYERCROP",
    "BEL", "BEML", "BERGEPAINT", "BHARATFORG", "BHARTIARTL", "BHEL", "BIKAJI",
    "BIOCON", "BIRLACORPN", "BLUEDARTTEX", "BLUEDART", "BORORENEW", "BOSCHLTD",
    "BPCL", "BRIGADE", "BRITANNIA", "BSE", "BSOFT",
    "CAMS", "CANBANK", "CANFINHOME", "CAPLIPOINT", "CARBORUNIV", "CASTROLIND",
    "CCL", "CDSL", "CEATLTD", "CENTRALBK", "CENTURYTEX", "CESC", "CGPOWER",
    "CHALET", "CHAMBLFERT", "CHOLAFIN", "CIPLA", "CMS", "COALINDIA", "COFORGE",
    "COLPAL", "CONCOR", "COROMANDEL", "CREDITACC", "CRISIL", "CROMPTON",
    "CSBBANK", "CUB",
    "DABUR", "DALBHARAT", "DATAMATICS", "DCMSHRIRAM", "DEEPAKFERT", "DEEPAKNTR",
    "DELHIBANK", "DELHIVERY", "DEVYANI", "DHANI", "DHANUKA", "DIVISLAB",
    "DIXON", "DLF", "DMART", "DRDLABS",
    "ECLERX", "EDELWEISS", "EICHERMOT", "ELECON", "ELGIEQUIP", "EMAMILTD",
    "EMKAY", "ENDURANCE", "EPL", "EQUITASBNK", "ERIS", "ESCORT",
    "EXIDEIND",
    "FINEORG", "FLUOROCHEM", "FORTIS", "FRETAIL", "FSL",
    "GAIL", "GALAXYSURF", "GLAND", "GLAXO", "GLENMARK", "GMRAIRPORT", "GMRINFRA",
    "GOCOLORS", "GODAWARI", "GODREJAGRO", "GODREJCP", "GODREJIND", "GODREJPROP",
    "GRANULES", "GRAPHITE", "GRASIM", "GREAVESCOT", "GSFC", "GSPL", "GUJGASLTD",
    "GULFOILLUB", "GVKPIL",
    "HAPPSTMNDS", "HAVELLS", "HCLTECH", "HDFCAMC", "HDFCBANK", "HDFCLIFE",
    "HEROMOTOCO", "HFCL", "HIKAL", "HINDALCO", "HINDCOPPER", "HINDPETRO",
    "HINDUNILVR", "HINDZINC", "HONAUT", "HSCL", "HUDCO",
    "IBULHSGFIN", "ICICIBANK", "ICICIGI", "ICICIPRULI", "IDBI", "IDFCFIRSTB",
    "IEX", "IGL", "IIFL", "IIFLWAM", "INDGN", "INDHOTEL", "INDIANB",
    "INDIAMART", "INDIGO", "INDIGOPNTS", "INDUSINDBK", "INDUSTOWER",
    "INFOSYS", "IOB", "IOC", "IPCALAB", "IRB", "IRCON", "IRCTC", "IREDA",
    "ISGEC", "ISMT", "ITCLTD", "ITC",
    "J&KBANK", "JBCHEPHARM", "JBMA", "JINDALSTEL", "JINDALSAW", "JKCEMENT",
    "JKLAKSHMI", "JKPAPER", "JSL", "JSWENERGY", "JSWINFRA", "JSWSTEEL",
    "JTEKTINDIA", "JUBLFOOD", "JUBLPHARMA",
    "KAJARIACER", "KALPATPOWR", "KANSAINER", "KAYNES", "KECL", "KEI", "KIOCL",
    "KIRLOSKAR", "KPIL", "KRBL", "KSCL", "KTKBANK",
    "L&TFH", "LALPATHLAB", "LATENTVIEW", "LAURUSLABS", "LAXMIMACH",
    "LT", "LTF", "LTIM", "LTTS", "LUXIND",
    "MAHABANK", "MAHINDRA", "MAHLIFE", "MAHLOG", "MANAPPURAM", "MARICO",
    "MARUTI", "MASTEK", "MAXHEALTH", "MCX", "METROPOLIS", "MFSL", "MGL",
    "MMTC", "MODI", "MOTHERSON", "MPHASIS", "MRF", "MUTHOOTFIN",
    "NATCOPHARM", "NATIONALUM", "NAVINFLUOR", "NBCC", "NCC", "NIAC", "NHPC",
    "NILKAMAL", "NLCINDIA", "NMDC", "NRBBEARING", "NTPC", "NUVAMA", "NUVOCO",
    "OBEROIRLTY", "OFSS", "OIL", "ONGC", "ORIENTELEC",
    "PAGEIND", "PEL", "PERSISTENT", "PETRONET", "PFC", "PFIZER", "PIDILITIND",
    "PIIND", "PNBHOUSING", "PNB", "POLYCAB", "POLYMED", "POONAWALLA", "POWERGRID",
    "PRESTIGE", "PRINCEPIPES", "PRSMJOHNSN", "PSUBNKBEES", "PVR", "PVRINOX",
    "RAMCOCEM", "RATNAMANI", "RAYMOND", "RBA", "RECLTD", "REDINGTON", "RELAXO",
    "RELIANCE", "ROUTE", "RVNL",
    "SAREGAMA", "SBICARD", "SBILIFE", "SBIN", "SCHAEFFLER", "SHREECEM",
    "SHRIRAMFIN", "SIEMENS", "SJVN", "SKFINDIA", "SOBHA", "SOLARA", "SONATSOFTW",
    "SOMANYCERA", "SRF", "STARHEALTH", "STLTECH", "SUBROS", "SUMICHEM",
    "SUNPHARMA", "SUNTV", "SUPREMEIND", "SURYAROSNI", "SUZLON",
    "SWANENERGY", "SWIGGY", "SYMPHONY",
    "TANLA", "TATACOMM", "TATACONSUM", "TATAELXSI", "TATAMOTORS", "TATAPOWER",
    "TATASTEEL", "TATATECH", "TCS", "TEAMLEASE", "TECHM", "TEJASNET",
    "TITAN", "TORNTPHARM", "TORNTPOWER", "TRIDENT", "TRENT", "TRIVENI",
    "TRVAIG", "TTML", "TV18BRDCST", "TVSMOTOR",
    "UBL", "UCOBANK", "ULTRACEMCO", "UNIONBANK", "UNITDSPR", "UNOMINDA",
    "UPL", "UTIAMFITP",
    "VBL", "VEDL", "VIJAYA", "VINATIORGA", "VOLTAS",
    "WIPRO", "WOCKPHARMA",
    "XPRO",
    "YESBANK",
    "ZEEL", "ZOMATO", "ZYDUSLIFE", "ZYDUSWELL",
]

# Deduplicated and sorted
NIFTY_500 = sorted(set(NIFTY_500))

def get_nifty500_symbols():
    """Return the Nifty 500 stock symbols as a sorted list."""
    return list(NIFTY_500)
