"""
Django settings for smallcase_project project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Load environment variables from .env file
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-oy&7^1-p0nvhtnqug9&#krywx*-(q(8&ay@j!@7!-1)(a0(96g')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

# Allow Railway domain and localhost
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,.railway.app,.up.railway.app').split(',') if h.strip()]

# CSRF trusted origins for Railway
# Include both http (localhost) and https (Railway production)
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in os.environ.get(
        'CSRF_TRUSTED_ORIGINS', 
        'http://localhost:8000,http://127.0.0.1:8000,https://*.railway.app,https://*.up.railway.app'
    ).split(',') if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'daphne',  # ASGI server for WebSocket support (must be first)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Django Sites Framework (required by Allauth)
    'django.contrib.sites',
    
    # Django Allauth - Authentication & Social Login
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    
    # Django OTP for Two-Factor Authentication
    'django_otp',
    'django_otp.plugins.otp_totp',
    
    'channels',  # Django Channels for real-time WebSocket messaging
    'corsheaders',
    'django_htmx',  # Django HTMX integration
    'import_export',  # Django Import-Export for admin data import/export
    'user',  # User authentication app
    'stocks',  # Stock basket management app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Language detection middleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django_htmx.middleware.HtmxMiddleware',  # HTMX middleware for request.htmx
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    
    # Django Allauth - Account management middleware
    'allauth.account.middleware.AccountMiddleware',
    
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smallcase_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': [
            BASE_DIR / 'stocks' / 'templates',
            BASE_DIR / 'user' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'environment': 'stocks.jinja2.environment',
        },
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'stocks'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smallcase_project.wsgi.application'
ASGI_APPLICATION = 'smallcase_project.asgi.application'

# Channel Layers for real-time WebSocket messaging
# Using in-memory channel layer for development
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}
# For production with Redis (higher performance, required for multi-server):
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [("127.0.0.1", 6379)],
#         },
#     },
# }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Use PostgreSQL in production (Railway), SQLite for local development

import dj_database_url


def _get_database_config():
    sqlite_db_name = str(BASE_DIR / 'smallcasedb')
    default_db_url = f'sqlite:///{sqlite_db_name}'
    database_url = os.environ.get('DATABASE_URL', '').strip()

    if not database_url:
        return dj_database_url.config(
            default=default_db_url,
            conn_max_age=600,
            conn_health_checks=True,
        )

    parsed = dj_database_url.parse(database_url)
    if parsed.get('ENGINE') == 'django.db.backends.postgresql':
        try:
            import psycopg2

            conn = psycopg2.connect(
                dbname=parsed.get('NAME'),
                user=parsed.get('USER'),
                password=parsed.get('PASSWORD'),
                host=parsed.get('HOST'),
                port=parsed.get('PORT'),
            )
            conn.close()
            return dj_database_url.config(
                default=database_url,
                conn_max_age=600,
                conn_health_checks=True,
            )
        except Exception:
            return {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': sqlite_db_name,
            }

    return dj_database_url.config(
        default=database_url or default_db_url,
        conn_max_age=600,
        conn_health_checks=True,
    )


DATABASES = {
    'default': _get_database_config()
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en'  # Default language

# Supported languages
LANGUAGES = [
    ('en', 'English'),
    ('hi', 'हिन्दी (Hindi)'),
    ('mr', 'मराठी (Marathi)'),
]

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True  # Enable internationalization

USE_L10N = True  # Enable localization

USE_TZ = True

# Path where translation files (.po and .mo) will be stored
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Add both project-level static/ and app-level static/ directories
STATICFILES_DIRS = []
if os.path.exists(os.path.join(BASE_DIR, 'static')):
    STATICFILES_DIRS.append(os.path.join(BASE_DIR, 'static'))

# Add stocks app static directory
stocks_static = os.path.join(BASE_DIR, 'stocks', 'static')
if os.path.exists(stocks_static):
    STATICFILES_DIRS.append(stocks_static)

# Whitenoise for serving static files in production
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True  # For development only
# For production, use:
# CORS_ALLOWED_ORIGINS = [
#     "https://m.media-amazon.com",
#     "https://example.com",
# ]

# Caching Configuration
# Local memory cache for development (simple and requires no additional setup)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'smallcase-cache',
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        },
        'TIMEOUT': 300,  # 5 minutes default
    }
}

# For production, consider using Redis for better performance and persistence:
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         }
#     }
# }

# Authentication settings
AUTH_USER_MODEL = 'user.User'  # Custom user model in user app
LOGIN_URL = 'user:login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'user:login'

# Custom authentication backend - allows login with email or username
AUTHENTICATION_BACKENDS = [
    'user.backends.EmailOrUsernameBackend',  # Custom backend in user app
    'django.contrib.auth.backends.ModelBackend',  # Default backend (fallback)
    'allauth.account.auth_backends.AuthenticationBackend',  # Django Allauth backend
]

# ============ Session Configuration ============
# Configure session cookies to work properly on Railway with HTTPS
# Language preference is stored in session, so this is critical for i18n
IS_RAILWAY = os.environ.get('RAILWAY_ENVIRONMENT') is not None

if IS_RAILWAY:
    # Production (Railway) - Use secure cookies with HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'  # Allow language change redirects
    CSRF_COOKIE_SAMESITE = 'Lax'
else:
    # Local development - Allow http cookies
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'

# Session engine - database-backed sessions for persistence
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_SAVE_EVERY_REQUEST = False  # Only save when modified (better performance)

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============ AI Chat Configuration ============
# Choose AI provider: 'groq' (default) or 'gemini'
AI_PROVIDER = os.environ.get('AI_PROVIDER', 'groq')

# Groq API Configuration (Free tier: 30 requests/minute)
# Get API key from: https://console.groq.com/keys
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')
GROQ_MODEL = os.environ.get('GROQ_MODEL', 'llama-3.3-70b-versatile')

# Google Gemini API Configuration (Free tier: 15 requests/minute)
# Get API key from: https://makersuite.google.com/app/apikey
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')
GEMINI_MODEL = os.environ.get('GEMINI_MODEL', 'gemini-1.5-flash')


# ============ Django Sites Framework ============
SITE_ID = 1


# ============ Django Allauth Configuration ============

# Account Settings
ACCOUNT_AUTHENTICATION_METHOD = 'email'  # Login with email instead of username
ACCOUNT_EMAIL_REQUIRED = True  # Email is required
ACCOUNT_USERNAME_REQUIRED = False  # Username is optional
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # Email verification is mandatory ('mandatory', 'optional', or 'none')
ACCOUNT_UNIQUE_EMAIL = True  # Ensure email addresses are unique
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True  # Auto-login after email confirmation
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3  # Email confirmation link expires in 3 days

# Login/Logout Settings
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5  # Max login attempts before lockout
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 300  # Lockout duration in seconds (5 minutes)
LOGIN_REDIRECT_URL = '/'  # Redirect after successful login
ACCOUNT_LOGOUT_REDIRECT_URL = '/'  # Redirect after logout
ACCOUNT_LOGOUT_ON_GET = False  # Require POST for logout (security)

# Password Settings
ACCOUNT_PASSWORD_MIN_LENGTH = 8  # Minimum password length

# Session Settings
ACCOUNT_SESSION_REMEMBER = True  # Remember user session
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True  # Ask for password twice during signup

# Email Confirmation
ACCOUNT_CONFIRM_EMAIL_ON_GET = True  # Confirm email on GET request (clicking link)

# Custom Adapter (for custom logic)
ACCOUNT_ADAPTER = 'user.adapters.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'user.adapters.CustomSocialAccountAdapter'

# Social Account Settings
SOCIALACCOUNT_AUTO_SIGNUP = True  # Automatically signup users with social accounts
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'  # Skip email verification for social accounts
SOCIALACCOUNT_QUERY_EMAIL = True  # Ask for email if not provided by social provider

# Social Account Providers Configuration
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'APP': {
            'client_id': os.environ.get('GOOGLE_OAUTH_CLIENT_ID', ''),
            'secret': os.environ.get('GOOGLE_OAUTH_CLIENT_SECRET', ''),
            'key': ''
        }
    },
    'github': {
        'SCOPE': [
            'user',
            'user:email',
        ],
        'APP': {
            'client_id': os.environ.get('GITHUB_OAUTH_CLIENT_ID', ''),
            'secret': os.environ.get('GITHUB_OAUTH_CLIENT_SECRET', ''),
            'key': ''
        }
    }
}


# ============ Email Configuration ============

# Email Backend
# For development, use console backend (prints emails to console)
# For production, use SMTP backend
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend'  # Default to console for development
)


# Gmail SMTP Configuration
# To use Gmail:
# 1. Enable 2-Step Verification in your Google Account
# 2. Generate an App Password: https://myaccount.google.com/apppasswords
# 3. Set EMAIL_BACKEND to 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
SERVER_EMAIL = os.environ.get('SERVER_EMAIL', EMAIL_HOST_USER)

# Alternative: SendGrid Configuration
# To use SendGrid:
# 1. Sign up at https://sendgrid.com/ (100 emails/day free)
# 2. Get your API key
# 3. Set these environment variables:
#    EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
#    EMAIL_HOST=smtp.sendgrid.net
#    EMAIL_PORT=587
#    EMAIL_USE_TLS=True
#    EMAIL_HOST_USER=apikey
#    EMAIL_HOST_PASSWORD=your_sendgrid_api_key


# ============ SMS Configuration (Twilio) ============

# Twilio Configuration
# Sign up at https://www.twilio.com/ (free trial with $15 credit)
# Get your Account SID and Auth Token from the console
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = os.environ.get('TWILIO_PHONE_NUMBER', '')  # Your Twilio phone number

# Alternative: MSG91 (Good for India)
MSG91_AUTH_KEY = os.environ.get('MSG91_AUTH_KEY', '')
MSG91_SENDER_ID = os.environ.get('MSG91_SENDER_ID', '')


# ============ OTP Configuration ============

# OTP Settings
OTP_TOTP_ISSUER = 'Smallcase Project'  # Name shown in authenticator apps
OTP_LOGIN_URL = '/login/'  # Redirect to login page after OTP verification


# ============ Custom Password Reset with OTP ============

# OTP expiry time (in seconds)
OTP_EXPIRY_TIME = 300  # 5 minutes

# OTP length
OTP_LENGTH = 6

# Max OTP attempts
MAX_OTP_ATTEMPTS = 3

# OTP cooldown (prevent spam)
OTP_COOLDOWN_TIME = 60  # 1 minute between OTP requests

