# Generated by Django 6.0 on 2026-06-25 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_tinyurl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('document_type', models.CharField(choices=[('annual_report', 'Annual Report'), ('earnings_call', 'Earnings Call Transcript'), ('investor_presentation', 'Investor Presentation'), ('research_report', 'Research Report'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('file', models.FileField(upload_to='stock_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_indexed', models.BooleanField(db_index=True, default=False)),
                ('chunk_count', models.IntegerField(default=0)),
                ('fiscal_year', models.CharField(blank=True, help_text='e.g. FY2025 or Q2-2025', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='stocks.stock')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['stock', 'document_type'], name='stocks_stoc_stock_i_2a3187_idx'), models.Index(fields=['is_indexed'], name='stocks_stoc_is_inde_9ad21b_idx')],
            },
        ),
    ]
