# Generated by Django 6.0 on 2026-06-25 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_ai_rag_stock_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('embedding', models.JSONField(help_text='Embedding vector as a list of floats')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='stocks.stockdocument')),
            ],
            options={
                'ordering': ['chunk_index'],
                'indexes': [models.Index(fields=['document'], name='stocks_docu_documen_9bf688_idx')],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
