# Generated by Django 6.0 on 2026-07-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_documentchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50, unique=True)),
                ('ltp', models.DecimalField(decimal_places=4, help_text='Last Traded Price', max_digits=12)),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('prev_close', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('volume', models.BigIntegerField(default=0)),
                ('change', models.DecimalField(blank=True, decimal_places=4, help_text='Absolute change from prev close', max_digits=10, null=True)),
                ('change_pct', models.DecimalField(blank=True, decimal_places=4, help_text='Percentage change from prev close', max_digits=8, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True, db_index=True, help_text='Last updated time (auto-set on save)')),
                ('source', models.CharField(choices=[('fyers', 'Fyers API'), ('dhan', 'DhanHQ'), ('manual', 'Manual / Test')], db_index=True, default='fyers', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, help_text='Raw JSON received from the webhook for debugging', null=True)),
            ],
            options={
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['symbol'], name='stocks_mark_symbol_04678d_idx'), models.Index(fields=['-timestamp'], name='stocks_mark_timesta_8e115b_idx'), models.Index(fields=['source'], name='stocks_mark_source_570010_idx')],
            },
        ),
    ]
