# Generated by Django 6.0 on 2026-07-03 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_add_markettick'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending — queued, not yet started'), ('ingesting', 'Ingesting PDF into ChromaDB'), ('analyzing', 'Agents Running'), ('done', 'Analysis Complete'), ('error', 'Error')], db_index=True, default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('current_step', models.CharField(blank=True, help_text='Human-readable progress message shown in the UI.', max_length=100)),
                ('quant_result', models.JSONField(blank=True, help_text='Agent 1 Quant: ROCE, D/E, P/E, Revenue CAGR, verdict.', null=True)),
                ('news_result', models.JSONField(blank=True, help_text='Agent 2 News: headlines, sentiment score, summary.', null=True)),
                ('governance_result', models.JSONField(blank=True, help_text='Agent 3 Governance: management commentary, red flags.', null=True)),
                ('final_decision', models.JSONField(blank=True, help_text='Agent 4 CIO: final BUY/HOLD/SELL decision + reasoning.', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, help_text='The PDF document that triggered this analysis (optional if re-using indexed data).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_jobs', to='stocks.stockdocument')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='stocks.stock')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stock', '-created_at'], name='stocks_anal_stock_i_1f929b_idx'), models.Index(fields=['status'], name='stocks_anal_status_40235b_idx')],
            },
        ),
    ]
