# Generated by Django 6.0 on 2026-07-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_add_analysis_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, help_text="Set to True to show this basket on all users' dashboards"),
        ),
    ]
