# Generated by Django 6.0 on 2026-07-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_basket_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='agent_thoughts',
            field=models.JSONField(blank=True, default=list, help_text='List of intermediate thoughts and steps from the agents'),
        ),
    ]
