# Generated by Django 6.0 on 2026-07-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_analysisjob_agent_thoughts'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandSupplyScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('sector', models.CharField(blank=True, db_index=True, max_length=100)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('demand_overlap_count', models.IntegerField(db_index=True, default=0, help_text='Number of timeframes where price is in a demand zone (0-3)')),
                ('supply_overlap_count', models.IntegerField(db_index=True, default=0, help_text='Number of timeframes where price is in a supply zone (0-3)')),
                ('quarterly_demand', models.BooleanField(default=False, help_text='Price in quarterly demand zone')),
                ('monthly_demand', models.BooleanField(default=False, help_text='Price in monthly demand zone')),
                ('weekly_demand', models.BooleanField(default=False, help_text='Price in weekly demand zone')),
                ('quarterly_supply', models.BooleanField(default=False, help_text='Price in quarterly supply zone')),
                ('monthly_supply', models.BooleanField(default=False, help_text='Price in monthly supply zone')),
                ('weekly_supply', models.BooleanField(default=False, help_text='Price in weekly supply zone')),
                ('strongest_zone_score', models.IntegerField(db_index=True, default=0, help_text='Highest zone strength score (0-100) across all detected zones')),
                ('zone_details', models.JSONField(blank=True, default=dict, help_text='Full JSON of all demand/supply zones for chart rendering')),
                ('scan_timestamp', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['-demand_overlap_count', '-strongest_zone_score'],
                'indexes': [models.Index(fields=['-demand_overlap_count', '-strongest_zone_score'], name='stocks_dema_demand__5d7ffa_idx'), models.Index(fields=['sector', '-demand_overlap_count'], name='stocks_dema_sector_c7ec2a_idx'), models.Index(fields=['-supply_overlap_count'], name='stocks_dema_supply__2515dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='DemandSupplyZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('zone_type', models.CharField(choices=[('demand', 'Demand Zone'), ('supply', 'Supply Zone')], db_index=True, max_length=10)),
                ('timeframe', models.CharField(choices=[('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], db_index=True, max_length=15)),
                ('proximal_line', models.DecimalField(decimal_places=2, help_text='Edge of zone closest to current price (entry trigger)', max_digits=12)),
                ('distal_line', models.DecimalField(decimal_places=2, help_text='Edge of zone furthest from current price (stop-loss reference)', max_digits=12)),
                ('formed_date', models.DateField(help_text='Date when the zone first formed')),
                ('strength_score', models.IntegerField(default=0, help_text='Zone strength score 0-100 based on freshness, tightness, move strength, volume')),
                ('is_fresh', models.BooleanField(default=True, help_text='True if price has NOT returned to test the zone since formation')),
                ('base_candle_count', models.IntegerField(default=1, help_text='Number of candles in the base consolidation (1-5, fewer = stronger)')),
                ('move_pct', models.DecimalField(decimal_places=2, default=0, help_text='Percentage move away from zone on breakout', max_digits=8)),
                ('sector', models.CharField(blank=True, db_index=True, max_length=100)),
                ('scan_date', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['-strength_score'],
                'indexes': [models.Index(fields=['symbol', 'zone_type', 'timeframe'], name='stocks_dema_symbol_da5ed2_idx'), models.Index(fields=['zone_type', '-strength_score'], name='stocks_dema_zone_ty_445e94_idx'), models.Index(fields=['sector', 'zone_type'], name='stocks_dema_sector_c27c4b_idx')],
            },
        ),
    ]
