# Generated by Django 6.0 on 2026-07-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_demandsupplyscanresult_demandsupplyzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandsupplyscanresult',
            name='daily_demand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandsupplyscanresult',
            name='daily_supply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandsupplyscanresult',
            name='min125_demand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandsupplyscanresult',
            name='min125_supply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandsupplyscanresult',
            name='min75_demand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandsupplyscanresult',
            name='min75_supply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='demandsupplyscanresult',
            name='monthly_demand',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='demandsupplyscanresult',
            name='monthly_supply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='demandsupplyscanresult',
            name='quarterly_demand',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='demandsupplyscanresult',
            name='quarterly_supply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='demandsupplyscanresult',
            name='weekly_demand',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='demandsupplyscanresult',
            name='weekly_supply',
            field=models.BooleanField(default=False),
        ),
    ]
